### PR TITLE
Switch to checks API for TaskCluster

### PR DESCRIPTION
**Pull request by stephenmcgruer**
This requires first landing a variant of
https://github.com/mozilla/community-tc-config/pull/129 for
https://github.com/web-platform-tests/wpt-tc-checks

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@jgraham is this what would be required for the decision task changes, or is it more in-depth?

(Note that TaskCluster is not yet enabled for this repo, deliberately.)

**Comment by stephenmcgruer** [comment]
The config change landed; https://github.com/mozilla/community-tc-config/pull/268

**Comment by jgraham** [comment]
This could be wrong, it could be right.

I think it's at least the right idea, but I'm not sure if it's right in detail e.g. if scopes also have to be added.

We might consider only adding the scopes to top-level tasks not dependent tasks like downloading artifacts. But we can experiment with that later.

**Comment by stephenmcgruer** [comment]
Sounds good to me, let's give it a try :)

**Comment by stephenmcgruer** [comment]
Ok, so we probably need to add some scopes; I got https://github.com/web-platform-tests/wpt-tc-checks/commit/fc965167e6baf498a8ad63d924aca86d6f1fa1ce#commitcomment-39146509 for a test PR.

The error includes:

```
Client ID static/taskcluster/github does not have sufficient scopes and is missing the following scopes:

{
  "AnyOf": [
    "queue:create-task:highest:proj-wpt/ci",
    "queue:create-task:very-high:proj-wpt/ci",
    "queue:create-task:high:proj-wpt/ci",
    "queue:create-task:medium:proj-wpt/ci",
    "queue:create-task:low:proj-wpt/ci",
    "queue:create-task:very-low:proj-wpt/ci",
    "queue:create-task:lowest:proj-wpt/ci"
  ]
}
```

Poking around to try to understand where these come from atm.

**Comment by stephenmcgruer** [comment]
Ah, we may need to add wpt-tc-checks to https://github.com/mozilla/community-tc-config/blob/master/config/projects/wpt.yml

**Comment by stephenmcgruer** [comment]
Sent https://github.com/mozilla/community-tc-config/pull/269

**Pull request merged**
